# CSE351
## HW1
##  Due: June 9th at 11.59 pm



#### Provide the codes and explanation all  in this   .ipynb file such that we can run it on Jupyter notebook.  When this file is run all outputs should be printed out. Make sure your file is bug-free otherwise you won't get credit. Upload the file on Blackboard in Assignments on due date. 

 **Note**: If you are not familiar with Numpy the below links help you
 to write the codes easily
- CSE351_L1.ipynb
- CSE351_L1.ipynb
- [Link 1](https://www.python-course.eu/matrix_arithmetic.php)
- [Link 2](https://www.oreilly.com/library/view/machine-learning-with/9781491989371/ch01.html)
- [Link 3](http://www2.lawrence.edu/fast/GREGGJ/Python/numpy/numpyLA.html)

- [Link 4](https://www.math.ubc.ca/~pwalls/math-python/linear-algebra/linear-algebra-scipy/)


**Q1**. Consider vector $x=[10,20]$ and matrix 
$S=\begin{bmatrix}
    3& 6  \\
    4& 8 \\
\end{bmatrix}$
- Compute $S\times x^T$ where $\times$ denotes matrix multiplication
- Compute the inverse of $S$
- Compute the trace of $S$
- Are the columns of $X$ linearly independent? explain
- What is the rank of $X$
- Compute $x \times S^{-1}\times x^T$ where $S^{-1}$ is inverse of $S$
- Write a code to calculate the inner product of the first and second column of $S$. You cannot use any loops and only allow to use matrix or vector operations.
- Calculate the norm of $S$
- Compute the mean of $S$ using inner product and $1$ vector
- If $y=[10,3]$, compute the Euclidean distance $x-y$
- We want to scale the elements of $x$ differently ---10 by 2 and 3 by 4 and sum the elements of the resulting vector. using vector operation perform the calculation 
    


**Q2**. Currency exchange matrix. We consider a set of n currencies, 
labeled $1,...,n$. (These might correspond to USD, RMB, EUR, and so on.) At a particular time the exchange or conversion rates among the n currencies are given by an $n \times n$ (exchange rate) matrix $R$, where $R_{ij}$ is the amount of currency $i$ that you can buy for one unit of currency $j$. (All entries of $R$ are positive.) The exchange rates include commission charges, so we have $R_{ji}R_{ij}< 1$ forall$i\not\equiv j$. You can assume that$R_{ii} =1$.
Suppose $y = R x$, where $x$ is a vector (with nonnegative entries) that 
represents the amounts of the currencies that we hold. What is $y_i$? 
Your answer should be in English no code needed.

In [1]:
import numpy as np

In [2]:
x = np.array([[10,20]])

In [3]:
S = np.array([[3,6], [4,8]])

In [4]:
x

array([[10, 20]])

In [5]:
S

array([[3, 6],
       [4, 8]])

a) Compute  𝑆×𝑥𝑇  where  ×  denotes matrix multiplication

In [7]:
S@x.T

array([[150],
       [200]])

b) Compute the inverse of  𝑆

In [9]:
np.linalg.inv(S)

LinAlgError: Singular matrix

The inverse of the matrix S cannot be determined because the determinant 
of the matrix is 0. Hence it is a singular matrix and its inverse does not exist.

c) Compute the trace of S

In [10]:
S.trace()

11

d) Are the columns of  𝑋  linearly independent? explain

x = [[10,20]] 

columns (in our case, the elements of x) is said to be linearly independent when 
    
    a1*x1 + a2*x2 = 0
        where x1 = 10, x2 = 20;

    [10, 20] * [a1, a2] = [0]

forms the augmented matrix 

    [10 20 | 0]
    
clearly 

    10 + 20 !=0 

thereby the coloumns of X are linearly dependent.

e) What is the rank of  𝑋

In [11]:
np.linalg.matrix_rank(S)

1

f) Compute  𝑥 × 𝑆^−1 × 𝑥^𝑇  where  𝑆^−1  is inverse of  𝑆

In [12]:
det = np.linalg.det(S)

if det == 0:
    print("The determinant is zero, therefore the inverse does not exist.")
    exit()


The determinant is zero, therefore the inverse does not exist.


Henceforth, the X x S^-1 x X^T cannot be computed.

g) Write a code to calculate the inner product of the first and second column of  𝑆 . You cannot use any loops and only allow to use matrix or vector operations.

In [5]:
import numpy as np

In [9]:
S = np.array([[3, 6], [4, 8]])
x = np.array([[10, 20]])

In [11]:
S

array([[3, 6],
       [4, 8]])

In [12]:
x

array([[10, 20]])

In [13]:
dot_product = np.dot(S[:,0], S[:,1])

In [14]:
print(dot_product)

50




h) Calculate the norm of S

In [15]:
np.linalg.norm(S)

11.180339887498949

i) Compute the mean of  𝑆  using inner product and  1  vector

In [17]:
col1mean = np.dot(np.ones(2), S[:,0])/2

In [19]:
col2mean = np.dot(np.ones(2), S[:,1])/2

In [20]:
row1mean = np.dot(np.ones(2), S[0,:])/2

In [21]:
row2mean = np.dot(np.ones(2), S[1,:])/2

In [22]:
col1mean

3.5

In [23]:
col2mean

7.0

In [24]:
row1mean

4.5

In [25]:
row2mean

6.0

j) If 𝑦=[10,3], compute the Euclidean distance  𝑥−𝑦

In [33]:
diff = x-y

In [35]:
diff = np.squeeze(np.asarray(diff))

In [36]:
diff

array([ 0, 17])

In [38]:
dot = np.dot(diff, diff)

In [39]:
pow(dot, 1/2)

17.0

Euclidean Distance (x-y) has been calculated to be 17 units.

k) We want to scale the elements of  𝑥  differently ---10 by 2 and 3 by 4 and sum the elements of the resulting vector. using vector operation perform the calculation

This vector operation can easily be done by a dot product. Dot product between the vectors y = [10,3] and a aribtrary vector a = [2,4]. 

In [42]:
a = np.array([2,4])

In [43]:
print(np.dot(y,a))

[32]




Q2. Currency exchange matrix. We consider a set of n currencies, labeled  1,...,𝑛 . (These might correspond to USD, RMB, EUR, and so on.) At a particular time the exchange or conversion rates among the n currencies are given by an  𝑛×𝑛  (exchange rate) matrix  𝑅 , where  𝑅𝑖𝑗  is the amount of currency  𝑖  that you can buy for one unit of currency  𝑗 . (All entries of  𝑅  are positive.) The exchange rates include commission charges, so we have  𝑅𝑗𝑖𝑅𝑖𝑗<1  forall 𝑖≢𝑗 . You can assume that 𝑅𝑖𝑖=1 . Suppose  𝑦=𝑅𝑥 , where  𝑥  is a vector (with nonnegative entries) that represents the amounts of the currencies that we hold. What is  𝑦𝑖 ? Your answer should be in English no code needed.


Yi will be the resulting vector with the equivalent amount of currencies in the exchanged rate. In the equation y = Rx, where 𝑥 is a vector (with nonnegative entries) that represents the amounts of the currencies that we hold, then the dot product of R and x will result in scalar value y, which is the equivalent amount of the currency that you will receive if you exchange your currency for it. 