# CSE351
## HW1
##  Due: June 9th at 11.59 pm



#### Provide the codes and explanation all  in this   .ipynb file such that we can run it on Jupyter notebook.  When this file is run all outputs should be printed out. Make sure your file is bug-free otherwise you won't get credit. Upload the file on Blackboard in Assignments on due date. 

 **Note**: If you are not familiar with Numpy the below links help you
 to write the codes easily
- CSE351_L1.ipynb
- CSE351_L1.ipynb
- [Link 1](https://www.python-course.eu/matrix_arithmetic.php)
- [Link 2](https://www.oreilly.com/library/view/machine-learning-with/9781491989371/ch01.html)
- [Link 3](http://www2.lawrence.edu/fast/GREGGJ/Python/numpy/numpyLA.html)

- [Link 4](https://www.math.ubc.ca/~pwalls/math-python/linear-algebra/linear-algebra-scipy/)


**Q1**. Consider vector $x=[10,20]$ and matrix 
$S=\begin{bmatrix}
    3& 6  \\
    4& 8 \\
\end{bmatrix}$
- Compute $S\times x^T$ where $\times$ denotes matrix multiplication
- Compute the inverse of $S$
- Compute the trace of $S$
- Are the columns of $X$ linearly independent? explain
- What is the rank of $X$
- Compute $x \times S^{-1}\times x^T$ where $S^{-1}$ is inverse of $S$
- Write a code to calculate the inner product of the first and second column of $S$. You cannot use any loops and only allow to use matrix or vector operations.
- Calculate the norm of $S$
- Compute the mean of $S$ using inner product and $1$ vector
- If $y=[10,3]$, compute the Euclidean distance $x-y$
- We want to scale the elements of $x$ differently ---10 by 2 and 3 by 4 and sum the elements of the resulting vector. using vector operation perform the calculation 
    


**Q2**. Currency exchange matrix. We consider a set of n currencies, 
labeled $1,...,n$. (These might correspond to USD, RMB, EUR, and so on.) At a particular time the exchange or conversion rates among the n currencies are given by an $n \times n$ (exchange rate) matrix $R$, where $R_{ij}$ is the amount of currency $i$ that you can buy for one unit of currency $j$. (All entries of $R$ are positive.) The exchange rates include commission charges, so we have $R_{ji}R_{ij}< 1$ forall$i\not\equiv j$. You can assume that$R_{ii} =1$.
Suppose $y = R x$, where $x$ is a vector (with nonnegative entries) that 
represents the amounts of the currencies that we hold. What is $y_i$? 
Your answer should be in English no code needed.

In [5]:
import numpy as np
from numpy import linalg as lg

In [9]:
S = np.matrix([[3,6], [4,8]])

In [11]:
print(S)

[[3 6]
 [4 8]]


In [13]:
x = np.array([[10,20]])

In [18]:
 S*x.T

matrix([[150],
        [200]])

In [20]:
lg.inv(S)

LinAlgError: Singular matrix

In [22]:
lg.det(S)

0.0

In [23]:
S.trace()

matrix([[11]])

In [25]:
np.trace(S)

11

In [26]:
lg.rank(S)

AttributeError: module 'numpy.linalg' has no attribute 'rank'

In [29]:
lg.matrix_rank(S)

1

In [31]:
lg.matrix_rank(S.T)

1

In [32]:
x*lg.inv(S)*x.T

LinAlgError: Singular matrix

In [33]:
S.norm()

AttributeError: 'matrix' object has no attribute 'norm'

In [34]:
lg.norm(S)

11.180339887498949

In [47]:
row1mean = (np.ones(1).dot((S[0,:])))/2
(S[0,:].dot(np.ones(2)))/2

matrix([[4.5]])