In [1]:
import numpy as np

matrixA = np.array([1,2,3],[4,5,6])

TypeError: data type not understood

In [9]:
x = np.array([[10,20]])

In [12]:
S = np.array([[3,6], [4,8]])

In [14]:
S

array([[3, 6],
       [4, 8]])

In [15]:
x.T

array([10, 20])

In [16]:
x

array([10, 20])

In [24]:
x.shape

(1, 2)

In [25]:
x.T

array([[10],
       [20]])

In [26]:
x.T*S

array([[ 30,  60],
       [ 80, 160]])

In [29]:
S*x.T

array([[ 30,  60],
       [ 80, 160]])

In [30]:
x.t

AttributeError: 'numpy.ndarray' object has no attribute 't'

In [31]:
x.T

array([[10],
       [20]])

In [32]:
S.shape

(2, 2)

In [34]:
S@x.T

array([[150],
       [200]])

In [4]:
import numpy as np

In [5]:
S = np.array([[3,6], [4,8]])

In [6]:
x = np.array([[10,20]])

In [7]:
S

array([[3, 6],
       [4, 8]])

In [8]:
x

array([[10, 20]])

In [9]:
S@x.T

array([[150],
       [200]])

In [15]:
S

array([[3, 6],
       [4, 8]])

In [16]:
S.trace()

11

In [17]:
np.linalg.matrix_rank(S)

1

In [18]:
np.linalg.norm(S)

11.180339887498949

In [19]:
S.mean()

5.25

In [20]:
S*1

array([[3, 6],
       [4, 8]])

In [21]:
(S*np.array([1],[1]))/4

TypeError: data type not understood

In [22]:
np.array([1],[1])

TypeError: data type not understood

In [23]:
np.matrix([1],[1])

TypeError: data type not understood

In [24]:
np.array([[1],[1]])

array([[1],
       [1]])

In [25]:
(S*np.array([[1,1]]))/4

array([[0.75, 1.5 ],
       [1.  , 2.  ]])

In [26]:
(S*np.array([[1,1]]))/4

array([[0.75, 1.5 ],
       [1.  , 2.  ]])

In [27]:
S.dot(np.array([[1,1]]))

ValueError: shapes (2,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)

In [28]:
np.array([[1,1]])

array([[1, 1]])

In [29]:
np.array([[1,1]]).dot(S)

array([[ 7, 14]])

In [30]:
(np.array([[1,1]]).dot(S))/4

array([[1.75, 3.5 ]])